{{- if .Values.route.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "deploypackage.fullname" . }}
  labels:
    {{- include "deploypackage.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: {{ include "deploypackage.fullname" . }}
    weight: 100
  port:
    targetPort: {{ .Values.route.targetServicePort }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
{{- end }}

